### ISSUE TITLE
When attaching to an SVG, translated position is relative to SVG dom node

### ISSUE THREAD

**Issue by maxfriedmann** [shipshapecode/tether#212] opened 2016-09-15 15:08 UTC
If I add a tether to an SVG the position gets calculated based on the relative position inside the SVG. Afterwards its displayed with those coordinates on the page, which is wrong.

Since the tether elements are not children of the SVG, setting that one to position:relative also doesn't work (which would make sub elements position absolutely to its relative parent). 

Any ideas how I can solve that?

**Comment by rwwagner90** [comment] 2019-09-30 12:16
@maxfriedmann I am not sure I understand the issue here. Could you provide an example?

**Comment by rwwagner90** [comment] 2019-10-23 19:34
Without an example, I am unsure how to fix this. Closing for now, but if anyone experiences something like this, please let us know!

**Closed by rwwagner90** 2019-10-23 19:34 UTC

**Comment by DiscoNova** [comment] 2019-10-23 23:17
Unfortunately, SVGs are the bastard children of XML. While they share tons of their API with your basic HTML-elements ... but ... there are still tons of hickups and other ****ups with them.
For reopening this issue, I believe a barebones sample of the problem would go a long way towards getting someone to work on it.
At the moment the problem is on the level of "it doesn't do what I want, how can I make it do what is needed" - which - naturally ... doesn't give developers too much to work with :(

**Comment by rwwagner90** [comment] 2019-10-23 23:37
@DiscoNova would wrapping the SVG in a div fix the issue?

**Comment by DiscoNova** [comment] 2019-10-23 23:40
Oh... I have absolutely no idea :) My comment was for @maxfriedmann :)

**Comment by DiscoNova** [comment] 2019-10-24 00:06
But... I've had my fair share of fights with SVGs in the past.

The problem (as I see it) is that the SVG's "viewport coordinate system" can easily differ from the "user coordinate system". And by "easily", I mean "almost certainly" these days when the graphics designers use tools such as Sketch to generate assets; these tools create recursive coordinate system within the exported SVG and ... while doing that, make every developer's lives miserable :D

To figure out where the target element is supposed to be ... instead of simply finding the element's bounding box which defines its canvas, we also might need to find out the target element's current transformation matrix in relation to the viewport (i.e. the "user coordinate system") ... which can be a true pain in the hindside :)

Thankfully there are APIs for doing exactly that in most browsers ... but figuring out when to use them and when not to ... again is not such a trivial task :(
