### ISSUE TITLE
Horizontal constraint

### ISSUE THREAD

**Issue by rayrutjes** [shipshapecode/tether#182] opened 2016-05-30 16:42 UTC
Here is what I get with my current config:
![image](https://cloud.githubusercontent.com/assets/5570853/15654542/7b3129d6-2695-11e6-98a2-b0d8b2a17b00.png)

Here the window is now overlapping the element from the right side so the element is moved like:
![image](https://cloud.githubusercontent.com/assets/5570853/15654555/8c1384e2-2695-11e6-98a7-930c744b8168.png)

Here is my config:

``` js
var tether = new Tether({
                element: $menu.get(0),
                target: this,
                attachment: 'top left',
                targetAttachment: 'bottom left',
                constraints: [
                    {
                        to: 'window',
                        attachment: 'both'
                    }
                ]
            });
```

I would like to keep my first case, and replace my second one with this:
![image](https://cloud.githubusercontent.com/assets/5570853/15654610/e153a8e2-2695-11e6-91e4-376c4b366074.png)

Is there a way to switch from:

```
attachment: 'top left',
targetAttachment: 'bottom left',
```

to

```
attachment: 'top right',
targetAttachment: 'bottom right',
```

when the window overlaps the element?

**Comment by rayrutjes** [comment] 2016-05-30 17:10
In the documentation, there is the exact case I want to reproduce:

```js
new Tether({
  element: yellowBox,
  target: greenBox,
  attachment: 'top left',
  targetAttachment: 'bottom left',
  constraints: [
    {
      to: 'scrollParent',
      attachment: 'together'
    }
  ]
});
```
In my case it does not work.

**Comment by TrevorBurnham** [comment] 2016-05-31 15:56
This should probably be the behavior, but as a temporary workaround you might want to try listening for the Tether instance's `'update'` event when it hits the constraint and updating both `attachment` and `targetAttachment` in response.

**Comment by rayrutjes** [comment] 2016-06-01 09:18
@TrevorBurnham thank you for pointing me to that solution, that will do if I get it to work.
Actually I properly found how to listen for the update event, but did not find how to apply my custom new attachment and target attachment.

Could you tell me how to change these values and apply the changes?

**Comment by rayrutjes** [comment] 2016-06-01 10:12
Here is what I came up to for now:
```
var tether = new Tether({
                element: $menu,
                target: this,
                attachment: 'top left',
                targetAttachment: 'bottom left',
                constraints: [
                    {
                        to: 'window',
                        attachment: 'together both'

                    }
                ]
            });
            
            tether.on('update', function(item) {
                if (item.attachment.left == 'right' && item.attachment.top == 'top' && item.targetAttachment.left == 'left' && item.targetAttachment.top == 'bottom') {
                    config.attachment = 'top right';
                    config.targetAttachment = 'bottom right';

                    tether.setOptions(config, false);
                }

            });
```

Which leads to other issues apparently.

Once we have changed the options, we do not detect anymore that there is enough place to fallback on the other display.
If found no viable configuration to disallow the box to be adjusted vertically.

**Comment by wonskarol** [comment] 2018-07-19 11:39
any progress on that?

**Comment by cibulka** [comment] 2019-08-14 12:34
For any google speeders: It seems the issue is fixed with this constraints setup:

```
constraints={[
  {
    to: 'window',
    attachment: 'together',
    pin: true,
  },
]}
```

Untested!

**Closed** 2020-02-20 02:00 UTC
